services:
  expenses-tracking-frontend:
    image: expenses-tracking-frontend:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: ${TAG:-latest}
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
        VITE_API_URL: ${VITE_API_URL}
        VITE_FEATURE_NEXTCLOUD: ${VITE_FEATURE_NEXTCLOUD:-false}
    container_name: expenses-frontend
    restart: unless-stopped
    ports:
      - '4173:80'
    environment:
      APP_VERSION: ${TAG:-latest}
